{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"goldengoose\",\"namespace\":\"default\"},\"spec\":{\"ports\":[{\"port\":80,\"targetPort\":8000}],\"selector\":{\"app\":\"goldengoose\",\"track\":\"prod\"},\"type\":\"LoadBalancer\"}}\n"
                },
                "creationTimestamp": "2018-12-05T09:49:44Z",
                "name": "goldengoose",
                "namespace": "default",
                "resourceVersion": "1248",
                "selfLink": "/api/v1/namespaces/default/services/goldengoose",
                "uid": "17e48787-f873-11e8-83e6-42010a840106"
            },
            "spec": {
                "clusterIP": "10.15.254.156",
                "externalTrafficPolicy": "Cluster",
                "ports": [
                    {
                        "nodePort": 32185,
                        "port": 80,
                        "protocol": "TCP",
                        "targetPort": 8000
                    }
                ],
                "selector": {
                    "app": "goldengoose",
                    "track": "prod"
                },
                "sessionAffinity": "None",
                "type": "LoadBalancer"
            },
            "status": {
                "loadBalancer": {
                    "ingress": [
                        {
                            "ip": "35.240.9.47"
                        }
                    ]
                }
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "creationTimestamp": "2018-12-05T09:48:13Z",
                "labels": {
                    "component": "apiserver",
                    "provider": "kubernetes"
                },
                "name": "kubernetes",
                "namespace": "default",
                "resourceVersion": "6",
                "selfLink": "/api/v1/namespaces/default/services/kubernetes",
                "uid": "e2074308-f872-11e8-83e6-42010a840106"
            },
            "spec": {
                "clusterIP": "10.15.240.1",
                "ports": [
                    {
                        "name": "https",
                        "port": 443,
                        "protocol": "TCP",
                        "targetPort": 443
                    }
                ],
                "sessionAffinity": "None",
                "type": "ClusterIP"
            },
            "status": {
                "loadBalancer": {}
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
